### ISSUE TITLE
coc.nvim

### ISSUE THREAD

**Issue by cj** [rafi/vim-config#119]
Hi @rafi,

I saw you tried coc.nvim https://github.com/rafi/vim-config/commit/53c60013ababf397f00feb0ef77b43bef00e1496, what are your thoughts on it?

**Comment by rafi** [comment]
Hi @cj. I've [tried][1] coc.nvim for a few weeks. I was really impressed on the amount of work chemzqm has done, creating a whole new eco-system around coc and extensions. My first impression was that it works great, feels fast, and looks really good.

My later impressions of working with coc.nvim is:
- Python takes a while to index whole project on vim enter
- Bash extension didn't work because it doesn't support node 12.x
- I didn't have a nice experience and outcome setting up Go

Finally, I've chosen neo/vim over many editors I've used in the past 27 years because I wanted to hack it and I don't like java/lisp/javascript/etc., I like vimscript and python, and had many years of improving my editing capabilities while hacking with vimscript. During the years, I lost my appetite for Javascript, hence typescript isn't my cup of tea. Evidently, I'm sticking with deoplete.

[1]: https://github.com/rafi/vim-config/blob/master/config/plugins.yaml#L384-L387

**Comment by rafi** [comment]
I'm pretty happy with Neovim's LSP support, prabirshrestha's asyncomplete plugin collection. I've also (locally) disabled ALE even, because diagnostics are included with the LSP setup helper I use, https://github.com/mattn/vim-lsp-settings.

Currently, I can only attest to Go, Python, bash, vim, yaml. I haven't tested client-side languages like js,css,html,etc.
Coc.nvim was sluggish and felt like it adds a lot of overhead. Reopen if you have any thoughts to add...
