### ISSUE TITLE
auto-completion doesn't work anymore since the switch to asyncomplete

### ISSUE THREAD

**Issue by mm1ke** [rafi/vim-config#143]
First, thanks for your awesome (neo)vim config.
Since some time i noticed that the completion doesn't work anymore like before. Whenever i was typing some word in a file i usually got some hints about already existing words.
Something like:
![Screenshot_20200415_214723](https://user-images.githubusercontent.com/2951173/79381813-d6790780-7f62-11ea-8e2a-ecb28778d405.png)

However, this doesn't work anymore since the commits starting from: f6d51e783f4a22a8987291d15e64fcb2c908584a

I'm not getting any suggestions at all. I already tried out to reinstall your config and also tried it on other systems, but i couldn't get it to work.

I'm on Linux (Linux 5.6.3-gentoo) with neovim:
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
```

Would be great to have this feature working again.

Thx

**Comment by rafi** [comment]
Hi @mm1ke, I've been trying asyncomplete instead of deoplete for a little while now. I'm using it with conjunction with the vim-lsp plugin, and vim-lsp-settings: https://github.com/mattn/vim-lsp-settings -- look here for usage details.

When a file is opened, run `:LspInstallServer [server-name]` (you can hit <kbd>Tab</kbd> for autocompletion server names.) Let me know how it works out for you.

**Comment by mm1ke** [comment]
Hi @rafi, thank you. This indeed helped to bring back auto completion. Didn't know that i had todo that in order to make it work again.
Going to close this issue
