### ISSUE TITLE
Enforcing fold to everything

### ISSUE THREAD

**Issue by zsinx6** [rafi/vim-config#211]
Every time I open a file the folding is there for everything:
![image](https://user-images.githubusercontent.com/3532625/131771816-2779b348-4305-4f0e-9f6d-a0ae0e35561a.png)

I was not able to figure out what was wrong there, can you help?

**Comment by rafi** [comment]
Hi @zsinx6.
1. Folding should be fixed with this new commit: [1ecd7444](https://github.com/rafi/vim-config/commit/1ecd7444adae066f4ad8bb25a453f37612636967#diff-625734aabf9700fd7533ef3146d43da98bf6afd2b7876c5d24244088d5047aefL252-R255)
2. I've disabled `lsp_signature` plugin in the meanwhile, it's a little buggy from time-to-time: 51c4558b

**Comment by zsinx6** [comment]
Now it works, thanks!
