### ISSUE TITLE
Lack of user plugins leads to error on startup

### ISSUE THREAD

**Issue by jellonek** [rafi/vim-config#287]
When user does not have any "user defined plugins" an error is shown during nvim startup with:
```
Invalid plugin spec {
  on_attach = <function 1>,
  setup = <function 2>
}
```
Commenting https://github.com/rafi/vim-config/blob/4026e9e92db017d9cd86142ddd8b6831cfdf9ef9/init.lua#L12 removes error message so I guess that there is some issue with https://github.com/rafi/vim-config/blob/4026e9e92db017d9cd86142ddd8b6831cfdf9ef9/lua/rafi/config/init.lua#L279 function.

**Comment by jellonek** [comment]
I have probably set wrong description of the issue (maybe it's not lack of plugins as clearly there are some files defined) but basically the issue lays in somewhere in these lines

**Comment by rafi** [comment]
Make you sure you don't have any leftovers from pre-lazy.nvim version:
1. Do you have a `lua/plugins.lua`? Is it valid to work with lazy.nvim?
2. Ensure you don't have any `lua/plugins/*` files from older version. Even not an empty directory (`lua/plugins`).

You won't see these files in `git status` because they are ignored. You can see them with: `git check-ignore */*`
As a user, you can use these gitignored files to add plugins, and install [extras](https://github.com/rafi/vim-config/tree/master/lua/rafi/plugins/extras).
