### ISSUE TITLE
Vim8 doesn't work after initial run with Neovim

### ISSUE THREAD

**Issue by yarinb** [rafi/vim-config#57]
This might be a dein issue.
I cloned the repository, launched neovim and initialization (dein mostly) completed successfully.

When I executed vim (8.0.1400_2), I got a bunch of errors. Looks like vim doesn't load any plugin from dein's cache:

> [dein] Done: (2018/01/07 12:37:38)Press ENTER or type command to continue
> ~ 1m 45s
> ❯ nvim ~/.vimrc <=== This works like a charm
> ~ 2s
> ❯ vim ~/.vimrc
> Error detected while processing function <SNR>21_theme_reload:
> line    5:
> E121: Undefined variable: g:colors_name
> E116: Invalid arguments for function writefile
> Error detected while processing /Users/yarinb/.config/nvim/config/theme.vim:
> line   37:
> E185: Cannot find color scheme 'hybrid'
> Press ENTER or type command to continue

When I tried it the other way around (first vim, than neovim) things looked better and I got the configuration workin on both.

**Comment by LudwigWS** [comment]
This caused by dein doesn't generate cache for vim.

In nvim dein's cache in ~/.cache/vim/dein/.cache/init.vim, otherwise in vim is in ~/.cache/vim/dein/.cache/vimrc. 

Both them should have ** The most important ** subfolder named .dein. So to solve this problem, just copy all files under init.vim to vimrc. 

Scripts gave below:

```sh
cd ~/.cache/vim/dein/.cache
rm -rf vimrc
cp -r init.vim/ vimrc
mv vimrc/rollbacks/nvim vimrc/rollbacks/Vim
```

**Comment by rafi** [comment]
Please let me know if this problem is still relevant.
